services:
  db:
    image: postgres:16
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: projeto3
      POSTGRES_DB: help_ipvc
    ports:
      - "5432:5432"
    volumes:
      - help_ipvc_pg:/var/lib/postgresql/data
volumes:
  help_ipvc_pg:

